name: "deploy"
on:
  workflow_call:
    inputs:
      deploy_to:
        required: true
        type: string
env:
  BASE_DIR: ${{ format('/etc/{0}', github.repository)  }}
  APP_LABEL: ${{ vars.APP_LABEL }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_to }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: get key
        env:
          DEPLOY_KEY_BASE64: ${{ secrets.DEPLOY_KEY_BASE64 }}
        shell: bash
        run: |
          echo -n $DEPLOY_KEY_BASE64  | base64 --decode > deploy_key
      


      - name: delete keys
        if: always()
        uses: atlas-it-gmbh/actions/cleanup-files@main
        with:
          file-list: "deploy_key"