name: "deploy"
on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: test
        uses: atlas-it-gmbh/actions/test@dev
